### ISSUE TITLE
freeze_support()

### ISSUE THREAD

**Issue by rougier** [AugustinChrtn/Reproduction#1]
Following README and running main.py using Python 3.12 I got a warning:

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
```

that seems to be repeated over and over again such that I don't know if it's only a warning or a bug.
How long (approximately) main.py is supposed to run ? I stopped after 5 to 10 minutes but maybe it's longer.

**Comment by AugustinChrtn** [comment]
Thank you for opening this issue @rougier. 

The problem seems to come from the fact that macOS and Windows handle multiprocessing in Python differently from Linux. I changed the code and managed to run it on Windows. Please tell me if it corrected the problem on your operating system as well.

I also added a message with an estimation of the total computation time when you launch main.py or parameter_fitting.py. main.py takes less than an hour to run on modern computers and parameter_fitting.py might take a few hours.

Please tell me if you have any other issue running the code.
All the best,
Augustin
